language: objective-c
osx_image: xcode9.1

before_install:
  - rvm install ruby-2.2.0
  - gem install cocoapods
script:
  - cd Example && pod install
  - xcodebuild test -workspace Vinculum.xcworkspace/ -scheme vinculum-Example  -destination 'platform=iOS Simulator,OS=11.1,name=iPhone 8'
